# Generated by Django 2.2.5 on 2019-11-08 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.DateField(verbose_name=datetime.datetime(2019, 11, 8, 19, 30, 26, 570428)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_purchased',
            field=models.DateField(verbose_name=datetime.datetime(2019, 11, 8, 19, 30, 26, 571501)),
        ),
    ]
